services:
  - type: web
    name: ai-stock-tracker
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install numpy==1.21.2
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-crash-detector-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.7

databases:
  - name: ai-crash-detector-db
    databaseName: ai_crash_detector
    plan: starter 