services:
  - type: web
    name: ai-stock-tracker
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-crash-detector-db
          property: connectionString

databases:
  - name: ai-crash-detector-db
    databaseName: ai_crash_detector
    plan: starter 